config/routes.rb
Rails.application.routes.draw do

  root :to => 'booksimpression#top'

  get 'books' => 'booksimpression#index'

  post 'books' => 'booksimpression#create'

  get 'books/:id' => 'booksimpression#show', as: 'book'

  get 'books/:id/edit' => 'booksimpression#edit', as:'edit_book'

  patch 'books/:id/' => 'booksimpression#update', as:'update_book'

  delete 'books/:id/' => 'booksimpression#destroy', as: 'destroy_book'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, :body, presence: true
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booksimpression_controller.rb
class BooksimpressionController < ApplicationController

  def top
  end


  def index
  	@books = Book.all
  	@book = Book.new
  end


  def create
    # １. データを新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end


  def show
  	@book = Book.find(params[:id])
  end


  def edit
  	@book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = 'Book was successfully destroyed.'
      redirect_to books_path
    end
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booksimpression_helper.rb
module BooksimpressionHelper
end

app/views/booksimpression/edit.html.erb
<h1>Editing Book</h1>


  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved: <br>
    <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
    <% end %>
  <% end %>


<%= form_for(@book, url: update_book_path) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %> <br>
  <%= f.submit 'Update Book' %>
  <%end%>

  <%= link_to "Show", book_path(@book.id) %>

  <%= link_to "Back", books_path %>

app/views/booksimpression/index.html.erb
<h1>Books</h1>


<table width="60%">

    <tr align="center">
      <th width="20%">Title</th>
      <th width="65%">Body</th>
    </tr>


　　<% @books.each do |book| %>
     <tr align="left">
       <th width="20%"><%= book.title %></th>
       <th width="65%"><%= book.body %></th>
       <th width="5%">
       	<span>
         <%=link_to "Show", book_path(book.id) %>
        </span>
       </th>

      <th width="5%">
       	<span>
         <%=link_to "Edit", edit_book_path(book.id) %>
        </span>
       </th>

       <th width="5%">
       	<span>
         <%=link_to "Destroy", destroy_book_path(book.id), method: :delete,"data-confirm" => "本当に削除しますか？" %>
        </span>
       </th>
      </tr>
    <% end %>

</table>



<h3>New book</h3>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved: <br>
    <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
    <% end %>
  <% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/booksimpression/show.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this book from being saved: <br>
    <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
    <% end %>
  <% end %>
<% end %>


<h4>Title</h4>
<%= @book.title %>

<h4>Body</h4>
<%= @book.body %> <br>


<%= link_to "Edit", edit_book_path(@book.id) %>

<%= link_to "Back", books_path %>

<!--<h4>Edit</h4>

<h4>back</h4>

app/views/booksimpression/top.html.erb
TOPページ

<h1>ようこそ Bookers へ！</h1>

<p>"Bookersでは、様々な書籍にあなたの意見や"</p>
<p>"印象を交換することができます"</p>

<span>
  <%=link_to "Start", books_path %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>
  </body>
</html>